# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
"""StepUp terminal user interface."""

import argparse
import asyncio
import contextlib
import os
import signal
import subprocess
import sys
import tempfile
import termios
import threading
from collections.abc import Callable
from decimal import Decimal
from functools import partial

import attrs
from path import Path

from .asyncio import stoppable_iterator, wait_for_path
from .cgroups import cgroup_scope_prefix
from .config import ConfigLoader
from .constants import DIRECTOR_LOG, JOBLOG_CSV, PERF_DATA, SQLLOG_CSV, SQLLOG_JSON, STEPUP_DIR
from .director import interpret_jobs
from .enums import ReturnCode
from .exceptions import TUIError
from .reporter import ReporterHandler
from .rpc import AsyncRPCClient, serve_socket_rpc
from .utils import parse_resources
from .watcher import WATCHER_AVAILABLE

__all__ = ()


DIRECTOR_KILL_GRACE = 15.0
"""Seconds the director gets to shut down after a terminal signal, before it is killed.

Comfortably longer than the director's own `INTERRUPT_GRACE`,
so that killing steps and reporting the outcome is tried first.
"""


def merge_resources(base: str | None, override: str | None) -> str:
    merged = {**parse_resources(base or ""), **parse_resources(override or "")}
    return ",".join(f"{k}:{v}" for k, v in merged.items())


def _normalize_targets(raw_targets: list[str], stepup_root: Path) -> tuple[list[Path], list[Path]]:
    """Resolve and validate `stepup build` target arguments against the project root.

    A raw target ending in `os.sep` is a directory target: everything under that
    subtree whose declared `need` is `DEFAULT` is elevated, best-effort (see
    `docs/advanced_topics/build_targets.md`). Everything else is an exact-file target,
    regardless of what exists on disk. The trailing slash is the only classifier;
    classification never looks at the file system.

    Parameters
    ----------
    raw_targets
        The raw target strings, as passed on the command line.
    stepup_root
        The absolute path of the StepUp project root.

    Returns
    -------
    targets
        The normalized, root-relative exact-file target paths.
    target_dirs
        The normalized, root-relative directory target paths, each carrying its
        trailing slash.

    Raises
    ------
    TUIError
        If a target is an empty string.
    """
    targets = []
    target_dirs = []
    for raw_target in raw_targets:
        if raw_target == "":
            raise TUIError("A target cannot be an empty string.")
        is_dir_target = raw_target.endswith(os.sep)
        target_abs = Path(raw_target).absolute()
        target_rel = target_abs.relpath(stepup_root).normpath()
        if is_dir_target:
            target_dirs.append(target_rel / "")
        else:
            targets.append(Path(target_rel))
    return targets, target_dirs


def _resolve_root_and_targets(
    raw_targets: list[str],
) -> tuple[Path, list[Path], list[Path]]:
    """Resolve the project root and normalize target arguments against it.

    Reads `${STEPUP_ROOT}` (falling back to the current working directory) and
    absolutizes it immediately: a relative `STEPUP_ROOT` must be interpreted
    against the *original* working directory, before `async_build` changes to
    the project root. Targets are likewise normalized before any `cd()`.

    Parameters
    ----------
    raw_targets
        The raw target strings, as passed on the command line.

    Returns
    -------
    stepup_root
        The absolute project root.
    targets
        The normalized, root-relative exact-file target paths.
    target_dirs
        The normalized, root-relative directory target paths, each carrying its
        trailing slash.
    """
    stepup_root = Path(os.getenv("STEPUP_ROOT", os.getcwd())).absolute()
    targets, target_dirs = _normalize_targets(raw_targets, stepup_root)
    return stepup_root, targets, target_dirs


def build_tool(args: argparse.Namespace, default_resources: str) -> None:
    try:
        asyncio.run(async_build(args, default_resources))
    except TUIError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(ReturnCode.INTERNAL.value)


def _terminal_broadcasts(sig: signal.Signals, pid: int) -> bool:
    """Whether the terminal driver already delivered `sig` to `pid` as well as to this process.

    Only `SIGINT` (Ctrl-C) is generated by the terminal driver, which sends it to every
    process in the foreground process group at once. That is the case exactly when this
    process and `pid` are both in the process group that owns the controlling terminal.
    A `SIGINT` sent explicitly (`kill -INT`) to a backgrounded StepUp does not qualify,
    and neither does any `SIGTERM`.

    Parameters
    ----------
    sig
        The signal that was received by this process.
    pid
        The process id of the director.

    Returns
    -------
    broadcast
        True if `pid` received `sig` from the terminal driver as well.
    """
    if sig != signal.SIGINT:
        return False
    try:
        # Query the controlling terminal itself: stdin may be redirected while the
        # process is still in the foreground process group.
        with open("/dev/tty") as tty:
            foreground_pgid = os.tcgetpgrp(tty.fileno())
        return foreground_pgid == os.getpgid(0) == os.getpgid(pid)
    except OSError:
        return False


@attrs.define
class TerminalSignalHandler:
    """Handle terminal signals received while the director subprocess is running.

    The director aborts the build on such a signal itself
    (see `DirectorHandler.interrupt`), so the work here is only to make sure it
    receives the signal, and to guarantee that the terminal user interface exits even when
    the director does not.
    """

    reporter_handler: ReporterHandler = attrs.field()
    """The reporter used to inform the user about the interruption."""

    process_director: asyncio.subprocess.Process = attrs.field()
    """The director subprocess, to forward signals to."""

    signum: signal.Signals | None = attrs.field(init=False, default=None)
    """The first terminal signal received, or `None` if the build was not interrupted."""

    _count: int = attrs.field(init=False, default=0)
    """The number of terminal signals received so far."""

    _kill_handle: asyncio.TimerHandle | None = attrs.field(init=False, default=None)
    """Handle of the scheduled `_kill_director` call, or `None` when none is pending."""

    def handle(self, sig: signal.Signals) -> None:
        """React to a terminal signal, escalating when it is received repeatedly."""
        self._count += 1
        if self._count == 1:
            self.signum = sig
            self.reporter_handler.report(
                "WARNING", f"Interrupted by {sig.name}. Waiting for the director to stop.", []
            )
        if self._count >= 3:
            self.reporter_handler.report("ERROR", "Killing the director (SIGKILL).", [])
            self._kill_director()
            return
        if not _terminal_broadcasts(sig, self.process_director.pid):
            # Only this process received the signal, so the director must be told separately.
            with contextlib.suppress(ProcessLookupError):
                self.process_director.send_signal(sig)
        self._arm_kill_timer()

    def close(self) -> None:
        """Cancel the pending last-resort kill, e.g. because the director exited in time."""
        if self._kill_handle is not None:
            self._kill_handle.cancel()
            self._kill_handle = None

    def _arm_kill_timer(self) -> None:
        """Schedule the last-resort kill, unless it is already scheduled.

        This guarantees the user gets the shell prompt back
        even when the director gets stuck on its way out.
        """
        if self._kill_handle is None:
            self._kill_handle = asyncio.get_running_loop().call_later(
                DIRECTOR_KILL_GRACE, self._kill_director
            )

    def _kill_director(self) -> None:
        self.close()
        with contextlib.suppress(ProcessLookupError):
            self.process_director.kill()


async def async_build(args: argparse.Namespace, default_resources: str) -> None:
    if WATCHER_AVAILABLE and args.watch_first:
        args.watch = True
    stepup_root, targets, target_dirs = _resolve_root_and_targets(args.targets)
    if stepup_root != Path.cwd():
        print("Changing to", stepup_root)
        stepup_root.cd()

    # Sanity check before creating a subdirectory.
    if not Path("plan.py").is_file():
        raise TUIError("File plan.py does not exist.")

    # Check if another StepUp director is already/still running.
    if DIRECTOR_LOG.exists():
        with open(DIRECTOR_LOG) as fh:
            try:
                line = next(fh)
                path_old_socket = line.split()[-1]
                if Path(path_old_socket).exists():
                    raise TUIError(
                        f"Old director still running? Socket still exists: {path_old_socket}"
                    )
            except StopIteration:
                pass

    # Create dir
    dir_stepup = STEPUP_DIR
    dir_stepup.makedirs_p()
    for path_log in dir_stepup.glob("*.log"):
        path_log.remove_p()

    with tempfile.TemporaryDirectory(prefix="stepup-") as dir_sockets:
        dir_sockets = Path(dir_sockets)

        # Create socket paths
        director_socket_path = dir_sockets / "director"
        reporter_socket_path = dir_sockets / "reporter"

        # Set up the reporter monitor
        stop_event = asyncio.Event()
        reporter_handler = ReporterHandler(args.progress, stop_event)
        task_reporter = asyncio.create_task(
            serve_socket_rpc(reporter_handler, reporter_socket_path, stop_event),
            name="reporter-rpc",
        )
        tasks = [task_reporter]

        # Launch director as background process
        njob = interpret_jobs(args.jobs)
        argv = []
        if args.perf is not None:
            argv.extend(["perf", "record", "-F", str(args.perf), "-i", "-g", "-o", PERF_DATA])
        argv.append(sys.executable)
        if args.perf is not None:
            argv.extend(["-X", "perf"])
        argv.extend(
            [
                "-m",
                "stepup.core.director",
                director_socket_path,
                f"--reporter={reporter_socket_path}",
                f"--jobs={njob}",
                f"--postpone-cap={args.postpone_cap}",
                f"--log-level={args.log_level}",
            ]
        )
        argv.extend(f"--target={target}" for target in targets)
        argv.extend(f"--target-dir={target_dir}" for target_dir in target_dirs)
        if args.forkserver:
            argv.append("--forkserver")
        if args.preload_modules:
            argv.append(f"--preload-modules={args.preload_modules}")
        if not args.clean:
            argv.append("--no-clean")
        if not args.duration:
            argv.append("--no-duration")
        if args.explain_rerun:
            argv.append("--explain-rerun")
        if args.keep_going:
            argv.append("--keep-going")
        if not args.fix_epoch:
            argv.append("--no-fix-epoch")
        if args.progress and reporter_handler.console.is_terminal:
            argv.append("--live-progress")
        args.resources = merge_resources(default_resources, args.resources)
        if args.resources:
            argv.append(f"--resources={args.resources}")
        if args.sqllog:
            argv.append("--sqllog")
        if args.joblog:
            argv.append("--joblog")
        if WATCHER_AVAILABLE:
            if args.watch:
                argv.append("--watch")
            if args.watch_first:
                argv.append("--watch-first")
        if args.yappi:
            argv.append("--yappi")
        if args.cgroup:
            cgroup_argv = cgroup_scope_prefix()
            argv = [*cgroup_argv, *argv, "--cgroup"]
        returncode = 1  # Internal error unless it is overridden later by the director subprocess
        try:
            with open(DIRECTOR_LOG, "w") as log_file:
                process_director = await asyncio.create_subprocess_exec(
                    *argv,
                    stdin=subprocess.DEVNULL,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                )
                # Install terminal signal handlers, to avoid internal tracebacks
                # when the user presses Ctrl-C or the process is killed by a SIGTERM.
                # The director aborts the build itself, so this waits for it rather than
                # exiting straight away, which would cut its shutdown short.
                signal_handler = TerminalSignalHandler(reporter_handler, process_director)
                loop = asyncio.get_running_loop()
                for sig in (signal.SIGINT, signal.SIGTERM):
                    loop.add_signal_handler(sig, signal_handler.handle, sig)
                # Instantiate keyboard interaction or work non-interactively
                if sys.stdin.isatty():
                    await wait_for_path(director_socket_path, stop_event)
                    task_keyboard = asyncio.create_task(
                        keyboard(director_socket_path, reporter_handler, stop_event),
                        name="keyboard",
                    )
                    tasks.append(task_keyboard)
                returncode = await process_director.wait()
                signal_handler.close()
                for sig in (signal.SIGINT, signal.SIGTERM):
                    loop.remove_signal_handler(sig)
            if returncode < 0:
                signal_name = signal.Signals(-returncode).name
                reporter_handler.report("ERROR", f"Director killed by {signal_name}", [])
                # The director never got to call back into reporter.shutdown(), which would
                # normally stop the progress bar's Live display and restore the cursor.
                reporter_handler.shutdown()
                # A negative return code is not a ReturnCode flag combination.
                returncode = ReturnCode.INTERNAL.value
            if signal_handler.signum is not None:
                # Record that the build was aborted, on top of whatever the director reported.
                # Without this, an interrupted build is indistinguishable from a completed one.
                returncode |= ReturnCode.INTERRUPTED.value
            stop_event.set()
        finally:
            try:
                await asyncio.gather(*tasks)
            except ConnectionRefusedError:
                reporter_handler.report("ERROR", "Could not connect to director", [])

    # Check if the director.log file has error messages
    with open(DIRECTOR_LOG) as fh:
        if any(("ERROR" in line) or ("CRITICAL" in line) for line in fh):
            reporter_handler.report("WARNING", f"Errors logged in {DIRECTOR_LOG}", [])

    sys.exit(returncode)


@contextlib.asynccontextmanager
async def iter_keystrokes(stop_event: asyncio.Event):
    """Yield keystrokes from stdin, one at a time, in raw mode, until `stop_event` is set.

    Reads happen in a background thread because putting stdin in non-blocking mode
    (e.g. via `asyncio.StreamReader`) also affects stdout and stderr when they share the
    same underlying open file description as stdin, which breaks `print` and `rich.print`
    for large output.
    """
    fd = sys.stdin.fileno()
    old_tcattr = termios.tcgetattr(fd)
    new_tcattr = termios.tcgetattr(fd)
    new_tcattr[3] &= ~(termios.ICANON | termios.ECHO)
    termios.tcsetattr(fd, termios.TCSAFLUSH, new_tcattr)
    loop = asyncio.get_running_loop()
    queue = asyncio.Queue()

    def _stdin_loop():
        while True:
            loop.call_soon_threadsafe(queue.put_nowait, sys.stdin.read(1))

    threading.Thread(target=_stdin_loop, daemon=True).start()
    try:
        yield stoppable_iterator(queue.get, stop_event)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_tcattr)


KEY_STROKE_HELP = """
   r = run     q = shutdown     d = drain     j = join     g = graph
"""


async def keyboard(
    director_socket_path: Path,
    reporter_handler: ReporterHandler,
    stop_event: asyncio.Event,
) -> None:
    async with iter_keystrokes(stop_event) as keys:
        async for ch in keys:
            if ch in "qjdrg":
                async with await AsyncRPCClient.socket(director_socket_path) as client:
                    if ch == "q":
                        reporter_handler.report("KEYBOARD", "Shutting down", [])
                        await client.call.shutdown()
                    elif ch == "j":
                        reporter_handler.report(
                            "KEYBOARD", "Waiting for all steps before shutdown.", []
                        )
                        await client.call.join()
                    elif ch == "d":
                        reporter_handler.report("KEYBOARD", "Putting the scheduler on hold.", [])
                        await client.call.drain()
                    elif ch == "r":
                        reporter_handler.report("KEYBOARD", "Restarting the builder.", [])
                        await client.call.run()
                    elif ch == "g":
                        await client.call.graph("graph")
                        reporter_handler.report(
                            "KEYBOARD", "Workflow graph written to graph.txt.", []
                        )
            else:
                pages = [("Keys", KEY_STROKE_HELP)]
                reporter_handler.report("KEYBOARD", f"Unsupported key {ch}", pages)


def _add_build_parser(subparsers, loader: ConfigLoader, name: str, help_text: str) -> str:
    """Register the build subparser under *name* and return its default resources.

    The argument definitions are identical for every subcommand name; only the
    subparser name and its help text differ.
    The parser's `prog` is pinned to `"stepup build"` instead of the default derived
    from *name*, because `ConfigLoader.patch_parser` derives the config section from `prog`.
    Configuration therefore always comes from the `"build"` section, regardless of *name*,
    so `stepup build` and its aliases share a single source of truth for configuration.
    The price is that an alias shows `usage: stepup build ...` in its help,
    which is a fair hint towards the canonical name.

    Parameters
    ----------
    subparsers
        The sub parser to add the build tool to.
    loader
        The configuration loader to override the default configuration with
        config file values.
    name
        The subcommand name to register (e.g. `"build"` or `"boot"`).
    help_text
        The help text shown for this subcommand.

    Returns
    -------
    default_resources
        The default value of the `--resources` argument, used to seed
        `merge_resources` in the build tool.
    """
    parser = subparsers.add_parser(
        name,
        prog="stepup build",
        help=help_text,
    )
    parser.add_argument(
        "targets",
        nargs="*",
        default=[],
        help="Build only these output files (and their required dependencies), "
        "instead of the full default workflow.",
    )
    parser.add_argument(
        "--cgroup",
        default=False,
        action=argparse.BooleanOptionalAction,
        help="Launch the director in its own cgroup, so that peak memory usage of the director and "
        "its children can be measured accurately. (Supported on Linux with systemd only.) "
        "Fails if not supported.",
    )
    parser.add_argument(
        "--clean",
        default=True,
        action=argparse.BooleanOptionalAction,
        help="Remove outdated output files.",
    )
    parser.add_argument(
        "--duration",
        default=True,
        action=argparse.BooleanOptionalAction,
        help="Use the duration of steps to optimize the execution order.",
    )
    parser.add_argument(
        "--explain-rerun",
        "-e",
        default=False,
        action=argparse.BooleanOptionalAction,
        help="Explain for every step with recording info why it cannot be skipped.",
    )
    parser.add_argument(
        "--keep-going",
        "-k",
        default=False,
        action=argparse.BooleanOptionalAction,
        help="Keep building steps whose inputs remain available after another step fails, "
        "instead of putting the scheduler on hold, like `make -k`. "
        "In-progress steps always finish regardless of this flag.",
    )
    parser.add_argument(
        "--jobs",
        "-j",
        type=Decimal,
        default=Decimal("1.0"),
        help="Number of jobs running in parallel. "
        "When given as a real number with digits after the decimal point, "
        "it is multiplied with the number of available cores. [default=%(default)s]",
    )
    parser.add_argument(
        "--joblog",
        default=False,
        action=argparse.BooleanOptionalAction,
        help="Record job-execution events (created, started, ended, completed) to "
        f"{JOBLOG_CSV}, for diagnosing scheduler/executor dispatch overhead.",
    )
    parser.add_argument(
        "--fix-epoch",
        default=True,
        action=argparse.BooleanOptionalAction,
        help="Set the SOURCE_DATE_EPOCH environment variable to 315532800. "
        "This corresponds to 1980-01-01 00:00:00 UTC. "
        "(If the variable is already set, it will be used as-is.) ",
    )
    parser.add_argument(
        "--forkserver",
        default=(sys.platform == "linux"),
        action=argparse.BooleanOptionalAction,
        help="Use a forkserver for Python step execution and file hashing "
        "to reduce startup overhead. [default: True on Linux, False elsewhere]",
    )
    parser.add_argument(
        "--perf",
        default=None,
        nargs="?",
        const="500",
        metavar="FREQ",
        help="Profile the director with perf, by default at a frequency of %(const)s Hz. "
        "(Only supported on Linux with perf installed.) "
        "Write --perf=FREQ when combining with build targets, "
        "since a bare --perf would otherwise consume the next target as the frequency.",
    )
    parser.add_argument(
        "--preload-modules",
        default=None,
        help="Comma-separated list of Python modules to pre-load into the forkserver. "
        "Only has effect when --forkserver is active. [default: none]",
    )
    parser.add_argument(
        "--progress",
        default=True,
        action=argparse.BooleanOptionalAction,
        help="Report progress information in the terminal user interface. "
        "(This can be useful to simplify and reduce the output.)",
    )
    parser.add_argument(
        "--postpone-cap",
        type=int,
        default=100,
        help="Maximum number of consecutive postpones (since the last success) before "
        "a step is failed instead of parked. A livelock guard. [default=%(default)s]",
    )
    resources_action = parser.add_argument(
        "--resources",
        "-r",
        type=str,
        default=None,
        help="Available resources for steps, e.g. 'cpu:4,gpu:1,memgb:16'. "
        "Merged with (not overriding) config files and STEPUP_BUILD_RESOURCES env var.",
    )
    parser.add_argument(
        "--sqllog",
        default=False,
        action=argparse.BooleanOptionalAction,
        help=f"Enable SQLite debug logging: append per-query timing rows to {SQLLOG_CSV} "
        f"as they execute, and write a query/call-site/plan index to {SQLLOG_JSON} "
        "when the director exits.",
    )
    if WATCHER_AVAILABLE:
        parser.add_argument(
            "--watch",
            "-w",
            default=False,
            action=argparse.BooleanOptionalAction,
            help="StepUp will watch for file changes after all runnable steps have been executed. "
            "By pressing r, it will rerun steps that have become pending due to the file changes. "
            "(Only supported on Linux.)",
        )
        parser.add_argument(
            "--watch-first",
            "-W",
            default=False,
            action=argparse.BooleanOptionalAction,
            help="Start the builder after observing the first file change in watch mode. "
            "This implies --watch. (Only supported on Linux.)",
        )
    parser.add_argument(
        "--yappi",
        default=False,
        action=argparse.BooleanOptionalAction,
        help="Profile the director with Yappi (must be installed). "
        "This produces a .stepup/director.prof file that can be analyzed with "
        "tools like SnakeViz.",
    )
    loader.patch_parser(parser, merge_handlers={"resources": merge_resources})
    return resources_action.default


def build_subcommand(subparsers, loader: ConfigLoader) -> Callable:
    """Define command-line arguments for the build tool.

    Parameters
    ----------
    subparsers
        The sub parser to add the build tool to.
    loader
        The configuration loader to override the default configuration with
        config file values.
    """
    default_resources = _add_build_parser(subparsers, loader, "build", "Build the StepUp workflow.")
    return partial(build_tool, default_resources=default_resources)


def boot_subcommand(subparsers, loader: ConfigLoader) -> Callable:
    """Define command-line arguments for the deprecated `boot` alias of `build`.

    Parameters
    ----------
    subparsers
        The sub parser to add the boot tool to.
    loader
        The configuration loader to override the default configuration with
        config file values.
    """
    default_resources = _add_build_parser(
        subparsers, loader, "boot", "Deprecated alias of 'stepup build'."
    )
    return partial(_deprecated_boot_tool, default_resources=default_resources)


def _deprecated_boot_tool(args: argparse.Namespace, default_resources: str) -> None:
    print(
        "Warning: 'stepup boot' is deprecated; use 'stepup build' instead.",
        file=sys.stderr,
    )
    build_tool(args, default_resources=default_resources)
