# StepUp Core provides the basic framework for the StepUp build tool.
# Copyright 2024-2026 Toon Verstraelen
#
# This file is part of StepUp Core.
#
# StepUp Core is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# StepUp Core is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --
"""Run examples."""

import os

import pytest
from path import Path

from stepup.core.pytest import run_example, run_plan

OVERWRITE_EXPECTED = "STEPUP_OVERWRITE_EXPECTED" in os.environ


@pytest.mark.parametrize(
    "name",
    [
        "absolute",
        "amend",
        "amend_delete_both",
        "amend_env_vars",
        "amend_missing_inp",
        "amend_missing_out",
        "amend_missing_vol",
        "amend_mixed",
        "amend_self_static",
        "amend_static",
        "amend_validate1",
        "amend_validate2",
        "awaited_detached",
        "call_args_file_json",
        "call_args_file_no_ext",
        "call_args_file_yaml",
        "call_chain",
        "call_conditional",
        "call_env",
        "call_fan_out",
        "call_fn_plan",
        "call_inp_known",
        "call_kwargs",
        "call_list",
        "call_minimal",
        "call_out_known",
        "call_plan_amends",
        "call_resources",
        "call_restart_change_args_file",
        "call_restart_change_inp",
        "call_restart_change_kwargs",
        "call_run_amends",
        "call_vol",
        "call_whitespace",
        "call_workdir",
        "clean_after",
        "clean_awaited1",
        "clean_awaited2",
        "clean_changed",
        "clean_dir",
        "clean_dir_static",
        "clean_drained_scheduler",
        "clean_nonexisting",
        "clean_detached",
        "copy_mkdir",
        "cyclic_dynamic",
        "cyclic_static",
        "drop_amend",
        "dynamic_module",
        "env_vars",
        "env_vars_amend",
        "env_vars_multi",
        "env_vars_path",
        "env_vars_subs",
        "env_vars_workdir",
        "error_cyclic_late",
        "error_env_var",
        "error_main_fails",
        "error_plan_no_shebang",
        "error_plan_not_executable",
        "error_runpy_no_shebang",
        "error_runpy_not_executable",
        "error_runsh_no_shebang",
        "error_runsh_not_executable",
        "error_runsh_opts",
        "error_static_dir",
        "error_step",
        "external_sources",
        "filter_deps_symlink",
        "getinfo",
        "here",
        "inp_digest",
        "input_check_changed",
        "input_check_deleted",
        "input_check_three",
        "input_check_two",
        "no_clean",
        "no_clean_awaited_detached",
        "no_data",
        "no_plan",
        "no_shebang",
        "no_static",
        "not_cyclic",
        "optional_amend",
        "optional_amend_twice",
        "optional_chain",
        "optional_change",
        "optional_change_sub",
        "optional_cleanup",
        "optional_convert",
        "optional_cross_plan",
        "output_not_created",
        "output_storage",
        "path_filter",
        "pending",
        "pending_cleanup",
        "pending_nested",
        "pending_shutdown",
        "permissions_file_rerun",
        "permissions_plan_rerun",
        "permissions_plan_restart",
        "permissions_step_rerun",
        "permissions_step_restart",
        "plan_inp",
        pytest.param("preload_modules", marks=pytest.mark.requires_fork_runpy),
        "record_subprocess",
        "recreate_elsewhere",
        "recursive_glob",
        "runpyep",
        "render_jinja_dict",
        "render_jinja_fail",
        "render_jinja_json",
        "render_jinja_python",
        "render_jinja_relpath",
        "render_jinja_toml",
        "render_jinja_yaml",
        "replay_nglob",
        "replay_static",
        "replay_static_tree",
        "replay_static_tree_plan",
        "reqdir_missing",
        "resource_multi",
        "resource_pool",
        "resource_skip",
        "resource_zero",
        "restart_add_missing",
        "restart_add_nglob",
        "restart_amend_concerted",
        "restart_blocked",
        "restart_changes",
        "restart_delete_nglob",
        "restart_detached",
        "restart_failed",
        "restart_fix_bug",
        "restart_input",
        "restart_mandatory",
        "restart_mode_change",
        "restart_nested",
        "restart_nochanges",
        "restart_shell_change",
        "restart_outdated_amend",
        "restart_output",
        "restart_queued",
        "restart_static_remove1",
        "restart_static_remove2",
        "restart_static_tree",
        "restart_static_tree_removed",
        "restart_step_changed",
        "script_cases",
        "script_cases_run_import",
        "script_cases_settings",
        "script_inp",
        "script_single",
        "script_single_optional",
        "script_single_run_import",
        "static",
        "static_abs",
        "static_after",
        "static_glob",
        "static_nglob",
        "static_nglob_partial",
        "static_nglob_recursive",
        "static_nglob_subdir",
        "static_tree1",
        "static_tree2",
        "static_tree_amend",
        "static_tree_nonexisting",
        "static_tree_step",
        "static_tree_sub",
        "subdir",
        "subprocess_output",
        "translate_external",
        "wait_first",
        "watch_add_missing",
        "watch_amended",
        "watch_awaited",
        "watch_blocked",
        "watch_boot",
        "watch_chain",
        "watch_failed",
        "watch_input",
        "watch_mandatory",
        "watch_middle",
        "watch_mixed",
        "watch_mode_change",
        "watch_move_dir_simple",
        "watch_nochanges",
        "watch_outdated_amend1",
        "watch_outdated_amend2",
        "watch_output",
        "watch_static_remove1",
        "watch_static_remove2",
        "watch_volatile",
        "watch_wanted",
        "warn_plan_non_plan",
        "whitespace",
        "workdir",
    ],
)
@pytest.mark.asyncio
async def test_example(name: str, path_tmp: Path):
    await run_example(Path("tests/examples") / name, path_tmp, OVERWRITE_EXPECTED)


@pytest.mark.parametrize(
    "name",
    [
        "amend",
        "not_cyclic",
        "optional_convert",
        "script_single",
        "static",
    ],
)
@pytest.mark.asyncio
async def test_plan(name: str, path_tmp: Path):
    await run_plan(Path("tests/examples") / name, path_tmp)
