# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Run examples."""

import os

import pytest
from path import Path

from stepup.core.pytest import run_example, run_plan

OVERWRITE_EXPECTED = "STEPUP_OVERWRITE_EXPECTED" in os.environ

EXAMPLES = [
    "absolute",
    "amend",
    "amend_delete_both",
    "amend_env_vars",
    "amend_env_vars_subs",
    "amend_missing_inp",
    "amend_missing_out",
    "amend_missing_vol",
    "amend_mixed",
    "amend_restart_restore",
    "amend_restart_skip",
    "amend_self_static",
    "amend_self_static_change",
    "amend_self_static_replay",
    "amend_self_static_restart",
    "amend_static",
    "amend_validate1",
    "amend_validate2",
    "amend_watch_restore",
    "awaited_detached",
    "build_target",
    "build_target_dir",
    "build_target_dir_mixed",
    "build_target_dir_resume",
    "build_target_invalid",
    "build_target_resume",
    "build_target_stale_decl",
    "build_target_stale_target",
    "build_target_static_resume",
    "call_args_file_json",
    "call_args_file_no_ext",
    "call_args_file_yaml",
    "call_chain",
    "call_conditional",
    "call_env",
    "call_fan_out",
    "call_fn_plan",
    "call_inp_known",
    "call_kwargs",
    "call_list",
    "call_minimal",
    "call_out_known",
    "call_plan_amends",
    "call_resources",
    "call_restart_change_args_file",
    "call_restart_change_inp",
    "call_restart_change_kwargs",
    "call_run_amends",
    "call_vol",
    "call_whitespace",
    "call_workdir",
    "clean_after",
    "clean_awaited1",
    "clean_awaited2",
    "clean_changed",
    "clean_dir",
    "clean_dir_static",
    "clean_drained_scheduler",
    "clean_nonexisting",
    "clean_detached",
    "command_callable",
    "config_sections",
    "copy_mkdir",
    "cyclic_dynamic",
    "cyclic_static",
    "detach_running_step",
    "drop_dynamic",
    "dynamic_module",
    "env_overrides",
    "env_vars",
    "env_vars_config_add",
    "env_vars_config_touch",
    "env_vars_multi",
    "env_vars_path",
    "env_vars_restart_set",
    "env_vars_restart_unset",
    "env_vars_restart_value",
    "env_vars_subs",
    "env_vars_workdir",
    "error_amend_while_holding",
    "error_cyclic_late",
    "error_detach_running",
    "error_detach_running_amend",
    "error_env_var",
    "error_main_fails",
    "error_output_becomes_dir",
    "error_plan_no_shebang",
    "error_plan_not_executable",
    "error_runpy_no_shebang",
    "error_runpy_not_executable",
    "error_runsh_no_shebang",
    "error_runsh_not_executable",
    "error_runsh_opts",
    "error_step",
    "error_stepup_dir",
    "external_sources",
    "filter_deps_symlink",
    "get_info",
    "glob_dir_outside_tree",
    "glob_dir_parent_of_static",
    "glob_justified_late",
    "glob_no_declare",
    "glob_output_after",
    "glob_output_before",
    "glob_overlapping",
    "glob_stepup_dir",
    "glob_unjustified_file",
    "glob_unjustified_skipped_step",
    "glob_unjustified_watch",
    "glob_volatile",
    "here",
    "hold_nested",
    "hold_orders_by_duration",
    "hold_skip_bypass",
    "inp_digest",
    "input_check_changed",
    "input_check_deleted",
    "input_check_defer",
    "input_check_three",
    "input_check_two",
    "keep_going",
    "no_clean",
    "no_clean_awaited_detached",
    "no_data",
    "no_plan",
    "no_shebang",
    "no_static",
    "not_cyclic",
    "not_cyclic_change",
    "not_cyclic_replay",
    "not_cyclic_restart",
    "optional_chain",
    "optional_change",
    "optional_change_sub1",
    "optional_change_sub2",
    "optional_cleanup",
    "optional_convert",
    "optional_convert_reselect",
    "optional_convert_restore",
    "optional_cross_plan",
    "optional_dynamic",
    "optional_dynamic_twice",
    "optional_recreate_deep_sink",
    "optional_recreate_stale_sink",
    "output_not_created",
    "output_storage",
    "path_filter",
    "pending",
    "pending_after_failure",
    "pending_cleanup",
    "pending_nested",
    "pending_shutdown",
    "permissions_file_rerun",
    "permissions_plan_rerun",
    "permissions_plan_restart",
    "permissions_step_rerun",
    "permissions_step_restart",
    "plan_inp",
    "preload_modules",
    "record_subprocess",
    "record_subprocess_shell",
    "recreate_elsewhere",
    "recursive_glob",
    "recycle_running",
    "relax_amend_liveness",
    "relax_amend_restart",
    "relax_amend_success",
    "runpyep",
    "render_jinja_dict",
    "render_jinja_fail",
    "render_jinja_json",
    "render_jinja_python",
    "render_jinja_relpath",
    "render_jinja_toml",
    "render_jinja_yaml",
    "replay_nglob",
    "replay_static",
    "replay_static_tree",
    "replay_static_tree_plan",
    "reqdir_missing",
    "defer_cap",
    "defer_cap_swallowed_error",
    "resource_multi",
    "resource_pool",
    "resource_skip",
    "resource_zero",
    "restart_add_missing",
    "restart_add_nglob",
    "restart_amend_concerted",
    "restart_blocked",
    "restart_changes",
    "restart_delete_nglob",
    "restart_detached",
    "restart_detached_self_static",
    "restart_failed",
    "restart_fix_bug",
    "restart_glob_first_match",
    "restart_input",
    "restart_mandatory",
    "restart_mode_change",
    "restart_nested",
    "restart_nochanges",
    "restart_shell_change",
    "restart_outdated_amend",
    "restart_output",
    "restart_queued",
    "restart_static_remove1",
    "restart_static_remove2",
    "restart_static_tree",
    "restart_static_tree_file_handover",
    "restart_static_tree_removed",
    "restart_static_tree_stale_build",
    "restart_step_changed",
    "script_cases",
    "script_cases_run_import",
    "script_cases_settings",
    "script_inp",
    "script_single",
    "script_single_optional",
    "script_single_run_import",
    "static",
    "static_abs",
    "static_after",
    "static_from_glob",
    "static_glob",
    "static_dirhash",
    "static_nglob",
    "static_nglob_recursive",
    "static_nglob_subdir",
    "static_pattern",
    "static_pattern_dir",
    "static_pattern_empty",
    "static_pattern_named",
    "static_pattern_overlap",
    "static_pattern_recursive_middle",
    "static_pattern_recursive_rejected",
    "static_pattern_restart_add",
    "static_pattern_restart_delete",
    "static_pattern_tree_overlap",
    "static_tree1",
    "static_tree2",
    "static_tree_amend",
    "static_tree_dirhash",
    "static_tree_file_after",
    "static_tree_file_handover",
    "static_tree_glob",
    "static_tree_glob_dir",
    "static_tree_glob_no_collision",
    "static_tree_nonexisting",
    "static_tree_root",
    "static_tree_step",
    "static_tree_sub",
    "static_tree_two_plans_file_first",
    "static_tree_two_plans_tree_first",
    "subdir",
    "subdir_import",
    "subprocess_output",
    "translate_external",
    "wait_first",
    "watch_add_missing",
    "watch_dynamic_change",
    "watch_dynamic_delete",
    "watch_dynamic_restore",
    "watch_awaited",
    "watch_blocked",
    "watch_boot",
    "watch_chain",
    "watch_failed",
    "watch_glob_delete",
    "watch_glob_delete_dir",
    "watch_glob_first_match",
    "watch_input",
    "watch_mandatory",
    "watch_middle",
    "watch_mixed",
    "watch_mode_change",
    "watch_move_dir_simple",
    "watch_nochanges",
    "watch_outdated_amend1",
    "watch_outdated_amend2",
    "watch_output",
    "watch_static_remove1",
    "watch_static_remove2",
    "watch_static_tree_glob",
    "watch_volatile",
    "watch_wanted",
    "warn_plan_non_plan",
    "whitespace",
    "workdir",
]

# Examples that can only run when StepUp uses the forkserver path.
EXAMPLES_REQUIRES_FORKSERVER = {"preload_modules"}


@pytest.mark.parametrize(
    "name",
    [
        pytest.param(name, marks=pytest.mark.requires_forkserver)
        if name in EXAMPLES_REQUIRES_FORKSERVER
        else name
        for name in EXAMPLES
    ],
)
async def test_example(name: str, path_tmp: Path):
    await run_example(Path("tests/examples") / name, path_tmp, OVERWRITE_EXPECTED)


def test_examples_list_has_all_dirs():
    """Every directory under `tests/examples` is listed in `EXAMPLES`."""
    dirs = {path.name for path in Path("tests/examples").dirs()}
    missing = dirs - set(EXAMPLES)
    assert not missing, f"Example directories not listed in EXAMPLES: {sorted(missing)}"


def test_examples_list_has_no_extra():
    """Every entry in `EXAMPLES` corresponds to a directory under `tests/examples`."""
    dirs = {path.name for path in Path("tests/examples").dirs()}
    extra = set(EXAMPLES) - dirs
    assert not extra, f"EXAMPLES entries without a directory: {sorted(extra)}"


@pytest.mark.parametrize(
    "name",
    [
        "amend",
        "command_callable",
        "not_cyclic",
        "optional_convert",
        "script_single",
        "static",
        "static_pattern",
    ],
)
async def test_plan(name: str, path_tmp: Path):
    await run_plan(Path("tests/examples") / name, path_tmp)
