name: pytest
on:
  push:
    branches:
     - main
    tags-ignore:
      - '**'
  pull_request:
jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install development version
        run: pip install -e .[dev]
      - name: Run pytest
        run: pytest -v
