# SPDX-FileCopyrightText: 2024 Toon Verstraelen <Toon.Verstraelen@UGent.be>
# SPDX-License-Identifier: LGPL-3.0-or-later
name: pytest
on:
  push:
    branches:
      # Run tests for change on the main branch ...
      - main
    tags-ignore:
      # ... but not for tags (avoids duplicate work) ...
      - '**'
    paths:
      # ... and only if relevant files have changed.
      - stepup/**
      - tests/**
      - pyproject.toml
      - .github/workflows/pytest.yaml
  pull_request:
    # Run tests on pull requests ...
    paths:
      # ... only if relevant files have changed.
      - stepup/**
      - tests/**
      - pyproject.toml
      - .github/workflows/pytest.yaml

jobs:
  tests:
    permissions:
      contents: read
    env:
      # Enforce strict checks instead of trying to repair fixable issues.
      STEPUP_DEBUG: 1
      # Duration measurements are disabled to make tests deterministic.
      STEPUP_BUILD_DURATION: 0
      # RPC timeout is set shorter to speed up tests in case of failures.
      STEPUP_SYNC_RPC_TIMEOUT: 10
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            python-version: '3.11'
            resolution: lowest-direct
          - runner: ubuntu-26.04
            python-version: '3.14'
            resolution: highest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - name: Install with the test dependencies
        run: uv pip install --system --resolution ${{ matrix.resolution }} -e .[tests]
      - name: Run fast unit tests
        run: pytest -vv -k "not test_example"
      - name: Run integration tests with forked subprocesses
        run: STEPUP_BUILD_FORKSERVER=1 pytest -vv tests/test_examples.py
      - name: Run integration tests with plain subprocesses
        run: STEPUP_BUILD_FORKSERVER=0 pytest -vv tests/test_examples.py
